### ISSUE TITLE
Unable to call invoice with all arguments

### ISSUE THREAD

**Issue by valerio-vaccaro** [BHBNETWORK/lightning-client-js#8]
The lib is unable to execute an **invoice** call passing **msatoshi**, **label**, **description** and **expiry** (as used in the c-lightning implementation).

I also suggest adding a full demonstration able to shows the way to call every command implemented.

**Comment by isghe** [comment]
`README.md` and `example.js` updated, with an example calling method `invoice`.

**Comment by isghe** [comment]
For now the example on calling method `invoice`, I think is enough on how to call other methods.
